title: Backend Engineering Notes
description: Java, Spring Boot, Microservices, Kafka, Design Patterns
remote_theme: just-the-docs/just-the-docs

url: https://mmedaram.github.io
baseurl: /backend-engineering-notes

source: docs

search_enabled: true

aux_links:
  GitHub Repository:
    - https://github.com/mmedaram/backend-engineering-notes

